# Generated by Django 2.2.1 on 2019-05-16 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boat',
            name='name',
            field=models.CharField(max_length=120),
        ),
    ]
